### rename jpm columns
### doesn't include risk weighted assets
jpm <- jpmorgan %>%
  rename(
    interest_income	="BI00650",
    interest_expense="BI01100",
    privisions="BI01200",
    noninterest_income="BI02000",
    noninterest_expense="BI02400",
    construction_domestic_offices="BIB0045",
    x1_x4family_residential_construction="BIB0125",
    other_construction="BIB0225",
    loans_secured_by_farmland="BIB0325",
    revolving_open_ended_loans_secured_by_x1_x4_family_residential = "BIB0425",
    closed_end_loans_secured_by_x1_x4_family_other = "BIB0445",
    closed_end_loans_secured_by_x1_x4_family_first_liens="BIB0525",
    closed_end_loans_secured_by_x1_x4_family_junior_liens="BIB0625",
    multifamily_residential_properties_domestic_offices="BIB0725",
    nonfarm_nonresidential_domestic_offices="BIB0745",
    owner_occupied_nonfarm_nonresidential="BIB0825",
    other_nonfarm_nonresidential="BIB0925",
    real_estate_foreign_offices="BIB1025",
    loans_to_depository_institutions_and_acceptances_of_other_banks="BIB1040",
    loans_to_US_banks_and_other_US_depository_institutions="BIB1125",
    loans_to_foreign_banks="BIB1225",
    loans_to_finance_agricultural_production="BIB1325",
    C_I_loans="BIB1345",
    C_I_loans_to_US_addresses="BIB1425",
    C_I_loans_to_non_US_addresses	="BIB1525",
    consumer_loans="BIB1540",
    credit_card_loans_to_individuals="BIB1601",
    consumer_loans_excluding_credit_cards	="BIB1607",
    automobile_loans_to_individuals="BIB1625",
    consumer_loans_excluding_credit_cards_and_automobiles="BIB1640",
    loans_to_foreign_governments_and_official_institutions="BIB1810",
    all_other_loans="BIB1910",
    lease_financing_receivables="BIB1945",
    leases_to_individuals="BIB2010",
    all_other_leases="BIB2110",
    total_net_chargeoffs="BIB2210",
    total_assets="BC01000",
    tier1_capital_ratio="BCR0180") %>%
  mutate(nim = interest_income - noninterest_income)


### convert data to quarterly
jpm_quarterly <- jpm %>%
  mutate(quarter = quarters(date),
         year = year(date),
         qtr_interest_income = ifelse(quarter == "Q1", interest_income,
                                      interest_income - lag(interest_income)),
         qtr_interest_expense = ifelse(quarter == "Q1", interest_expense,
                                       interest_expense - lag(interest_expense)),
         qtr_noninterest_income = ifelse(quarter == "Q1", noninterest_income,
                                         noninterest_income - lag(noninterest_income)),
         qtr_noninterest_expense = ifelse(quarter == "Q1", noninterest_expense,
                                          noninterest_expense - lag(noninterest_expense)),
         qtr_construction_domestic_offices = ifelse(quarter == "Q1", construction_domestic_offices,
                                                    construction_domestic_offices - lag(construction_domestic_offices)),
         qtr_x1_x4family_residential_construction = ifelse(quarter == "Q1", x1_x4family_residential_construction,
                                                           x1_x4family_residential_construction - lag(x1_x4family_residential_construction)),
         qtr_other_construction = ifelse(quarter == "Q1", other_construction,
                                         other_construction - lag(other_construction)),
         qtr_loans_secured_by_farmland = ifelse(quarter == "Q1", loans_secured_by_farmland,
                                                loans_secured_by_farmland - lag(loans_secured_by_farmland)),
         qtr_revolving_open_ended_loans_secured_by_x1_x4_family_residential = ifelse(quarter == "Q1", revolving_open_ended_loans_secured_by_x1_x4_family_residential,
                                                                                     revolving_open_ended_loans_secured_by_x1_x4_family_residential - lag(revolving_open_ended_loans_secured_by_x1_x4_family_residential)),
         qtr_closed_end_loans_secured_by_x1_x4_family_other = ifelse(quarter == "Q1", closed_end_loans_secured_by_x1_x4_family_other,
                                                                     closed_end_loans_secured_by_x1_x4_family_other - lag(closed_end_loans_secured_by_x1_x4_family_other)),
         qtr_closed_end_loans_secured_by_x1_x4_family_first_liens = ifelse(quarter == "Q1", closed_end_loans_secured_by_x1_x4_family_first_liens,
                                                                           closed_end_loans_secured_by_x1_x4_family_first_liens - lag(closed_end_loans_secured_by_x1_x4_family_first_liens)),
         qtr_multifamily_residential_properties_domestic_offices = ifelse(quarter == "Q1", multifamily_residential_properties_domestic_offices,
                                                                          multifamily_residential_properties_domestic_offices - lag(multifamily_residential_properties_domestic_offices)),
         qtr_nonfarm_nonresidential_domestic_offices = ifelse(quarter == "Q1", nonfarm_nonresidential_domestic_offices,
                                                              nonfarm_nonresidential_domestic_offices - lag(nonfarm_nonresidential_domestic_offices)),
         qtr_owner_occupied_nonfarm_nonresidential = ifelse(quarter == "Q1", owner_occupied_nonfarm_nonresidential,
                                                            owner_occupied_nonfarm_nonresidential - lag(owner_occupied_nonfarm_nonresidential)),
         qtr_other_nonfarm_nonresidential = ifelse(quarter == "Q1", other_nonfarm_nonresidential,
                                                   other_nonfarm_nonresidential - lag(other_nonfarm_nonresidential)),
         qtr_real_estate_foreign_offices = ifelse(quarter == "Q1", real_estate_foreign_offices,
                                                  real_estate_foreign_offices - lag(real_estate_foreign_offices)),
         qtr_loans_to_depository_institutions_and_acceptances_of_other_banks = ifelse(quarter == "Q1", loans_to_depository_institutions_and_acceptances_of_other_banks,
                                                                                      loans_to_depository_institutions_and_acceptances_of_other_banks - lag(loans_to_depository_institutions_and_acceptances_of_other_banks)),
         qtr_loans_to_US_banks_and_other_US_depository_institutions = ifelse(quarter == "Q1", loans_to_US_banks_and_other_US_depository_institutions,
                                                                             loans_to_US_banks_and_other_US_depository_institutions - lag(loans_to_US_banks_and_other_US_depository_institutions)),
         qtr_loans_to_foreign_banks = ifelse(quarter == "Q1", loans_to_foreign_banks,
                                             loans_to_foreign_banks - lag(loans_to_foreign_banks)),
         qtr_loans_to_finance_agricultural_production = ifelse(quarter == "Q1", loans_to_finance_agricultural_production,
                                                               loans_to_finance_agricultural_production - lag(loans_to_finance_agricultural_production)),
         qtr_C_I_loans = ifelse(quarter == "Q1", C_I_loans,
                                C_I_loans - lag(C_I_loans)),
         qtr_C_I_loans_to_US_addresses = ifelse(quarter == "Q1", C_I_loans_to_US_addresses,
                                                C_I_loans_to_US_addresses - lag(C_I_loans_to_US_addresses)),
         qtr_consumer_loans = ifelse(quarter == "Q1", consumer_loans,
                                     consumer_loans - lag(consumer_loans)),
         qtr_consumer_loans_excluding_credit_cards = ifelse(quarter == "Q1", consumer_loans_excluding_credit_cards,
                                                            consumer_loans_excluding_credit_cards - lag(consumer_loans_excluding_credit_cards)),
         qtr_credit_card_loans_to_individuals = ifelse(quarter == "Q1", credit_card_loans_to_individuals,
                                                       credit_card_loans_to_individuals - lag(credit_card_loans_to_individuals)),
         qtr_automobile_loans_to_individuals = ifelse(quarter == "Q1", automobile_loans_to_individuals,
                                                      automobile_loans_to_individuals - lag(automobile_loans_to_individuals)),
         qtr_consumer_loans_excluding_credit_cards_and_automobiles = ifelse(quarter == "Q1", consumer_loans_excluding_credit_cards_and_automobiles,
                                                                            consumer_loans_excluding_credit_cards_and_automobiles - lag(consumer_loans_excluding_credit_cards_and_automobiles)),
         qtr_loans_to_foreign_governments_and_official_institutions = ifelse(quarter == "Q1", loans_to_foreign_governments_and_official_institutions,
                                                                             loans_to_foreign_governments_and_official_institutions - lag(loans_to_foreign_governments_and_official_institutions)),
         qtr_all_other_loans = ifelse(quarter == "Q1", all_other_loans,
                                      all_other_loans - lag(all_other_loans)),
         qtr_lease_financing_receivables = ifelse(quarter == "Q1", lease_financing_receivables,
                                                  lease_financing_receivables - lag(lease_financing_receivables)),
         qtr_leases_to_individuals = ifelse(quarter == "Q1", leases_to_individuals,
                                            leases_to_individuals - lag(leases_to_individuals)),
         qtr_all_other_leases = ifelse(quarter == "Q1", all_other_leases,
                                       all_other_leases - lag(all_other_leases)),
         qtr_total_net_chargeoffs = ifelse(quarter == "Q1", total_net_chargeoffs,
                                           total_net_chargeoffs - lag(total_net_chargeoffs)),
         qtr_total_assets = ifelse(quarter == "Q1", total_assets,
                                   total_assets - lag(total_assets))) %>%
  group_by(year, quarter) %>%
  summarise(qtr_interest_income = last(qtr_interest_income),
            qtr_interest_expense = last(qtr_interest_expense),
            qtr_noninterest_income = last(qtr_noninterest_income),
            qtr_noninterest_expense = last(qtr_noninterest_expense),
            qtr_construction_domestic_offices = last(qtr_construction_domestic_offices),
            qtr_x1_x4family_residential_construction = last(qtr_x1_x4family_residential_construction),
            qtr_other_construction = last(qtr_other_construction),
            qtr_loans_secured_by_farmland = last(qtr_loans_secured_by_farmland),
            qtr_revolving_open_ended_loans_secured_by_x1_x4_family_residential = last(qtr_revolving_open_ended_loans_secured_by_x1_x4_family_residential),
            qtr_closed_end_loans_secured_by_x1_x4_family_other = last(qtr_closed_end_loans_secured_by_x1_x4_family_other),
            qtr_closed_end_loans_secured_by_x1_x4_family_first_liens = last(qtr_closed_end_loans_secured_by_x1_x4_family_first_liens),
            qtr_multifamily_residential_properties_domestic_offices = last(qtr_multifamily_residential_properties_domestic_offices),
            qtr_nonfarm_nonresidential_domestic_offices = last(qtr_nonfarm_nonresidential_domestic_offices),
            qtr_owner_occupied_nonfarm_nonresidential = last(qtr_owner_occupied_nonfarm_nonresidential),
            qtr_other_nonfarm_nonresidential = last(qtr_other_nonfarm_nonresidential),
            qtr_real_estate_foreign_offices = last(qtr_real_estate_foreign_offices),
            qtr_loans_to_depository_institutions_and_acceptances_of_other_banks = last(qtr_loans_to_depository_institutions_and_acceptances_of_other_banks),
            qtr_loans_to_US_banks_and_other_US_depository_institutions = last(qtr_loans_to_US_banks_and_other_US_depository_institutions),
            qtr_loans_to_foreign_banks = last(qtr_loans_to_foreign_banks),
            qtr_loans_to_finance_agricultural_production = last(qtr_loans_to_finance_agricultural_production),
            qtr_C_I_loans = last(qtr_C_I_loans),
            qtr_consumer_loans = last(qtr_consumer_loans),
            qtr_consumer_loans_excluding_credit_cards = last(qtr_consumer_loans_excluding_credit_cards),
            qtr_credit_card_loans_to_individuals = last(qtr_credit_card_loans_to_individuals),
            qtr_automobile_loans_to_individuals = last(qtr_automobile_loans_to_individuals),
            qtr_consumer_loans_excluding_credit_cards_and_automobiles = last(qtr_consumer_loans_excluding_credit_cards_and_automobiles),
            qtr_loans_to_foreign_governments_and_official_institutions = last(qtr_loans_to_foreign_governments_and_official_institutions),
            qtr_all_other_loans = last(all_other_loans),
            qtr_lease_financing_receivables = last(qtr_lease_financing_receivables),
            qtr_leases_to_individuals = last(qtr_leases_to_individuals),
            qtr_all_other_leases = last(qtr_all_other_leases),
            qtr_total_net_chargeoffs = last(qtr_total_net_chargeoffs),
            qtr_total_assets = last(qtr_total_assets)) %>%
  ungroup()